classdef unittest2 < matlab.uitest.TestCase
    %test menu UI
    properties
        ui;

    end
    
    methods
        function start(self)
            addpath('../../src');
            board = chessboard();
            self.ui = app_define();
            back  = define_back(self.ui);
            self.ui.init_define(board,back)
        end        

    end

    methods(Test)
        %T1.6  
        %T1.6.1 without operating chess
        function no_operate_chess_test(testCase)
            testCase.start()
            testCase.press(testCase.ui.Button)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.press(testCase.ui.Button_2)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.press(testCase.ui.Button_3)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.press(testCase.ui.Button_4)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.press(testCase.ui.Button_5)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.press(testCase.ui.Button_6)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.press(testCase.ui.Button_7)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.press(testCase.ui.Button_8)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.press(testCase.ui.Button_9)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.press(testCase.ui.Button_10)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.press(testCase.ui.Button_11)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.press(testCase.ui.Button_12)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.press(testCase.ui.Button_13)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.press(testCase.ui.Button_14)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.press(testCase.ui.Button_15)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.press(testCase.ui.Button_16)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.press(testCase.ui.Button_17)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.press(testCase.ui.Button_18)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.press(testCase.ui.Button_19)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.press(testCase.ui.Button_20)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            close all force;
        end
        %T1.6.2
        function operate_chess1_test(testCase)
            testCase.start()
            testCase.press(testCase.ui.B1)
            testCase.press(testCase.ui.Button)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[1 1 0 0 ;1 1 0 0 ;0 0 0 0 ; 0 0 0 0; 0 0 0 0])
            testCase.press(testCase.ui.B1)
            testCase.press(testCase.ui.Button)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B1)
            testCase.press(testCase.ui.Button_2)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 1 1 0 ;0 1 1 0 ;0 0 0 0 ; 0 0 0 0; 0 0 0 0])
            testCase.press(testCase.ui.B1)
            testCase.press(testCase.ui.Button_2)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))


            testCase.press(testCase.ui.B1)
            testCase.press(testCase.ui.Button_3)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 1 1 ;0 0 1 1 ;0 0 0 0 ; 0 0 0 0; 0 0 0 0])
            testCase.press(testCase.ui.B1)
            testCase.press(testCase.ui.Button_3)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B1)
            testCase.press(testCase.ui.Button_4)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))
            testCase.verifyEqual(testCase.ui.Label.Text,'无效操作')
            
            testCase.press(testCase.ui.B1)
            testCase.press(testCase.ui.Button_5)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ;1 1 0 0 ;1 1 0 0 ; 0 0 0 0; 0 0 0 0])
            testCase.press(testCase.ui.B1)
            testCase.press(testCase.ui.Button_5)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B1)
            testCase.press(testCase.ui.Button_6)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ;0 1 1 0 ;0 1 1 0 ; 0 0 0 0; 0 0 0 0])
            testCase.press(testCase.ui.B1)
            testCase.press(testCase.ui.Button_6)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B1)
            testCase.press(testCase.ui.Button_7)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ;0 0 1 1 ;0 0 1 1 ; 0 0 0 0; 0 0 0 0])
            testCase.press(testCase.ui.B1)
            testCase.press(testCase.ui.Button_7)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B1)
            testCase.press(testCase.ui.Button_8)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))
            testCase.verifyEqual(testCase.ui.Label.Text,'无效操作')

            testCase.press(testCase.ui.B1)
            testCase.press(testCase.ui.Button_9)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ; 0 0 0 0;1 1 0 0 ;1 1 0 0 ; 0 0 0 0])
            testCase.press(testCase.ui.B1)
            testCase.press(testCase.ui.Button_9)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B1)
            testCase.press(testCase.ui.Button_10)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ; 0 0 0 0;0 1 1 0 ;0 1 1 0 ; 0 0 0 0])
            testCase.press(testCase.ui.B1)
            testCase.press(testCase.ui.Button_10)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B1)
            testCase.press(testCase.ui.Button_11)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ; 0 0 0 0;0 0 1 1 ;0 0 1 1 ; 0 0 0 0])
            testCase.press(testCase.ui.B1)
            testCase.press(testCase.ui.Button_11)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B1)
            testCase.press(testCase.ui.Button_12)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))
            testCase.verifyEqual(testCase.ui.Label.Text,'无效操作')

            testCase.press(testCase.ui.B1)
            testCase.press(testCase.ui.Button_13)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ; 0 0 0 0; 0 0 0 0;1 1 0 0 ;1 1 0 0 ])
            testCase.press(testCase.ui.B1)
            testCase.press(testCase.ui.Button_13)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B1)
            testCase.press(testCase.ui.Button_14)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ; 0 0 0 0; 0 0 0 0;0 1 1 0 ;0 1 1 0 ])
            testCase.press(testCase.ui.B1)
            testCase.press(testCase.ui.Button_14)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B1)
            testCase.press(testCase.ui.Button_15)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ; 0 0 0 0; 0 0 0 0;0 0 1 1 ;0 0 1 1 ])
            testCase.press(testCase.ui.B1)
            testCase.press(testCase.ui.Button_15)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B1)
            testCase.press(testCase.ui.Button_16)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))
            testCase.verifyEqual(testCase.ui.Label.Text,'无效操作')

            testCase.press(testCase.ui.B1)
            testCase.press(testCase.ui.Button_17)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))
            testCase.verifyEqual(testCase.ui.Label.Text,'无效操作')
            testCase.press(testCase.ui.B1)
            testCase.press(testCase.ui.Button_18)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))
            testCase.verifyEqual(testCase.ui.Label.Text,'无效操作')
            testCase.press(testCase.ui.B1)
            testCase.press(testCase.ui.Button_19)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))
            testCase.verifyEqual(testCase.ui.Label.Text,'无效操作')
            testCase.press(testCase.ui.B1)
            testCase.press(testCase.ui.Button_20)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))
            testCase.verifyEqual(testCase.ui.Label.Text,'无效操作')
            close all force;
        end
        %T1.6.3
        function operate_chess2_test(testCase)
            testCase.start()
            testCase.press(testCase.ui.B2)
            testCase.press(testCase.ui.Button)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[2 2 0 0 ;0 0 0 0 ;0 0 0 0 ; 0 0 0 0; 0 0 0 0])
            testCase.verifyEqual(testCase.ui.B2_put,true)
            testCase.press(testCase.ui.B2)
            testCase.press(testCase.ui.Button)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))
            testCase.verifyEqual(testCase.ui.B2_put,false)

            testCase.press(testCase.ui.B2)
            testCase.press(testCase.ui.Button_2)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 2 2 0 ;0 0 0 0 ;0 0 0 0 ; 0 0 0 0; 0 0 0 0])
            testCase.press(testCase.ui.B2)
            testCase.press(testCase.ui.Button_2)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))


            testCase.press(testCase.ui.B2)
            testCase.press(testCase.ui.Button_3)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 2 2 ;0 0 0 0 ;0 0 0 0 ; 0 0 0 0; 0 0 0 0])
            testCase.verifyEqual(testCase.ui.B2_put,true)
            testCase.press(testCase.ui.B2)
            testCase.press(testCase.ui.Button_3)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B2)
            testCase.press(testCase.ui.Button_4)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))
            testCase.verifyEqual(testCase.ui.Label.Text,'无效操作')
            
            testCase.press(testCase.ui.B2)
            testCase.press(testCase.ui.Button_5)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ;2 2 0 0 ;0 0 0 0 ; 0 0 0 0; 0 0 0 0])
            testCase.verifyEqual(testCase.ui.B2_put,true)
            testCase.press(testCase.ui.B2)
            testCase.press(testCase.ui.Button_5)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B2)
            testCase.press(testCase.ui.Button_6)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ;0 2 2 0 ;0 0 0 0 ; 0 0 0 0; 0 0 0 0])
            testCase.verifyEqual(testCase.ui.B2_put,true)
            testCase.press(testCase.ui.B2)
            testCase.press(testCase.ui.Button_6)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B2)
            testCase.press(testCase.ui.Button_7)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ;0 0 2 2 ;0 0 0 0 ; 0 0 0 0; 0 0 0 0])
            testCase.press(testCase.ui.B2)
            testCase.press(testCase.ui.Button_7)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B2)
            testCase.press(testCase.ui.Button_8)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))
            testCase.verifyEqual(testCase.ui.Label.Text,'无效操作')

            testCase.press(testCase.ui.B2)
            testCase.press(testCase.ui.Button_9)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ; 0 0 0 0;2 2 0 0 ;0 0 0 0 ; 0 0 0 0])
            testCase.press(testCase.ui.B2)
            testCase.press(testCase.ui.Button_9)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B2)
            testCase.press(testCase.ui.Button_10)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ; 0 0 0 0;0 2 2 0 ;0 0 0 0 ; 0 0 0 0])
            testCase.press(testCase.ui.B2)
            testCase.press(testCase.ui.Button_10)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B2)
            testCase.press(testCase.ui.Button_11)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ; 0 0 0 0;0 0 2 2 ;0 0 0 0 ; 0 0 0 0])
            testCase.press(testCase.ui.B2)
            testCase.press(testCase.ui.Button_11)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B2)
            testCase.press(testCase.ui.Button_12)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))
            testCase.verifyEqual(testCase.ui.Label.Text,'无效操作')

            testCase.press(testCase.ui.B2)
            testCase.press(testCase.ui.Button_13)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ; 0 0 0 0; 0 0 0 0;2 2 0 0 ;0 0 0 0 ])
            testCase.press(testCase.ui.B2)
            testCase.press(testCase.ui.Button_13)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B2)
            testCase.press(testCase.ui.Button_14)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ; 0 0 0 0; 0 0 0 0;0 2 2 0 ;0 0 0 0 ])
            testCase.press(testCase.ui.B2)
            testCase.press(testCase.ui.Button_14)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B2)
            testCase.press(testCase.ui.Button_15)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ; 0 0 0 0; 0 0 0 0;0 0 2 2 ;0 0 0 0 ])
            testCase.press(testCase.ui.B2)
            testCase.press(testCase.ui.Button_15)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B2)
            testCase.press(testCase.ui.Button_16)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))
            testCase.verifyEqual(testCase.ui.Label.Text,'无效操作')

            testCase.press(testCase.ui.B2)
            testCase.press(testCase.ui.Button_17)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ; 0 0 0 0; 0 0 0 0;0 0 0 0;2 2 0 0  ])
            testCase.press(testCase.ui.B2)
            testCase.press(testCase.ui.Button_17)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B2)
            testCase.press(testCase.ui.Button_18)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ; 0 0 0 0; 0 0 0 0;0 0 0 0;0 2 2 0  ])
            testCase.press(testCase.ui.B2)
            testCase.press(testCase.ui.Button_18)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B2)
            testCase.press(testCase.ui.Button_19)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ; 0 0 0 0; 0 0 0 0;0 0 0 0;0 0 2 2  ])
            testCase.press(testCase.ui.B2)
            testCase.press(testCase.ui.Button_19)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B2)
            testCase.press(testCase.ui.Button_20)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))
            testCase.verifyEqual(testCase.ui.Label.Text,'无效操作')
            close all force;
        end
        %T1.6.4
        function operate_chess3_test(testCase)
            testCase.start()
            testCase.press(testCase.ui.B3)
            testCase.press(testCase.ui.Button)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[3 0 0 0 ;3 0 0 0 ;0 0 0 0 ; 0 0 0 0; 0 0 0 0])
            testCase.press(testCase.ui.B3)
            testCase.press(testCase.ui.Button)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B3)
            testCase.press(testCase.ui.Button_2)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 3 0 0 ;0 3 0 0 ;0 0 0 0 ; 0 0 0 0; 0 0 0 0])
            testCase.press(testCase.ui.B3)
            testCase.press(testCase.ui.Button_2)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))


            testCase.press(testCase.ui.B3)
            testCase.press(testCase.ui.Button_3)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 3 0 ;0 0 3 0 ;0 0 0 0 ; 0 0 0 0; 0 0 0 0])
            testCase.press(testCase.ui.B3)
            testCase.press(testCase.ui.Button_3)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B3)
            testCase.press(testCase.ui.Button_4)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 3 ;0 0 0 3 ;0 0 0 0 ; 0 0 0 0; 0 0 0 0])
            testCase.press(testCase.ui.B3)
            testCase.press(testCase.ui.Button_4)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))
            
            testCase.press(testCase.ui.B3)
            testCase.press(testCase.ui.Button_5)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0;3 0 0 0 ;3 0 0 0 ;0 0 0 0 ;  0 0 0 0])
            testCase.press(testCase.ui.B3)
            testCase.press(testCase.ui.Button_5)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B3)
            testCase.press(testCase.ui.Button_6)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0;0 3 0 0 ;0 3 0 0 ;0 0 0 0 ;  0 0 0 0])
            testCase.press(testCase.ui.B3)
            testCase.press(testCase.ui.Button_6)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))


            testCase.press(testCase.ui.B3)
            testCase.press(testCase.ui.Button_7)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0;0 0 3 0 ;0 0 3 0 ;0 0 0 0 ;  0 0 0 0])
            testCase.press(testCase.ui.B3)
            testCase.press(testCase.ui.Button_7)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B3)
            testCase.press(testCase.ui.Button_8)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0;0 0 0 3 ;0 0 0 3 ;0 0 0 0 ;  0 0 0 0])
            testCase.press(testCase.ui.B3)
            testCase.press(testCase.ui.Button_8)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B3)
            testCase.press(testCase.ui.Button_9)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ; 0 0 0 0;3 0 0 0 ;3 0 0 0 ; 0 0 0 0])
            testCase.press(testCase.ui.B3)
            testCase.press(testCase.ui.Button_9)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B3)
            testCase.press(testCase.ui.Button_10)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ; 0 0 0 0;0 3 0 0 ;0 3 0 0 ; 0 0 0 0])
            testCase.press(testCase.ui.B3)
            testCase.press(testCase.ui.Button_10)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B3)
            testCase.press(testCase.ui.Button_11)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ; 0 0 0 0;0 0 3 0 ;0 0 3 0 ; 0 0 0 0])
            testCase.press(testCase.ui.B3)
            testCase.press(testCase.ui.Button_11)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B3)
            testCase.press(testCase.ui.Button_12)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ; 0 0 0 0;0 0 0 3 ;0 0 0 3 ; 0 0 0 0])
            testCase.press(testCase.ui.B3)
            testCase.press(testCase.ui.Button_12)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B3)
            testCase.press(testCase.ui.Button_13)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ; 0 0 0 0; 0 0 0 0;3 0 0 0 ;3 0 0 0 ])
            testCase.press(testCase.ui.B3)
            testCase.press(testCase.ui.Button_13)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B3)
            testCase.press(testCase.ui.Button_14)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ; 0 0 0 0; 0 0 0 0;0 3 0 0 ;0 3 0 0 ])
            testCase.press(testCase.ui.B3)
            testCase.press(testCase.ui.Button_14)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))


            testCase.press(testCase.ui.B3)
            testCase.press(testCase.ui.Button_15)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ; 0 0 0 0; 0 0 0 0;0 0 3 0 ;0 0 3 0 ])
            testCase.press(testCase.ui.B3)
            testCase.press(testCase.ui.Button_15)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B3)
            testCase.press(testCase.ui.Button_16)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0; 0 0 0 0 ; 0 0 0 0;0 0 0 3 ;0 0 0 3 ])
            testCase.press(testCase.ui.B3)
            testCase.press(testCase.ui.Button_16)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))
            

            testCase.press(testCase.ui.B3)
            testCase.press(testCase.ui.Button_17)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))
            testCase.verifyEqual(testCase.ui.Label.Text,'无效操作')
            testCase.press(testCase.ui.B3)
            testCase.press(testCase.ui.Button_18)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))
            testCase.verifyEqual(testCase.ui.Label.Text,'无效操作')
            testCase.press(testCase.ui.B3)
            testCase.press(testCase.ui.Button_19)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))
            testCase.verifyEqual(testCase.ui.Label.Text,'无效操作')
            testCase.press(testCase.ui.B3)
            testCase.press(testCase.ui.Button_20)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))
            testCase.verifyEqual(testCase.ui.Label.Text,'无效操作')
            close all force;
        end
        %T1.6.5
        function operate_chess4_test(testCase)
            testCase.start()
            testCase.press(testCase.ui.B4)
            testCase.press(testCase.ui.Button)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[4 0 0 0 ;4 0 0 0 ;0 0 0 0 ; 0 0 0 0; 0 0 0 0])
            testCase.press(testCase.ui.B4)
            testCase.press(testCase.ui.Button)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B4)
            testCase.press(testCase.ui.Button_2)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 4 0 0 ;0 4 0 0 ;0 0 0 0 ; 0 0 0 0; 0 0 0 0])
            testCase.press(testCase.ui.B4)
            testCase.press(testCase.ui.Button_2)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))


            testCase.press(testCase.ui.B4)
            testCase.press(testCase.ui.Button_3)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 4 0 ;0 0 4 0 ;0 0 0 0 ; 0 0 0 0; 0 0 0 0])
            testCase.press(testCase.ui.B4)
            testCase.press(testCase.ui.Button_3)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B4)
            testCase.press(testCase.ui.Button_4)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 4 ;0 0 0 4 ;0 0 0 0 ; 0 0 0 0; 0 0 0 0])
            testCase.press(testCase.ui.B4)
            testCase.press(testCase.ui.Button_4)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))
            
            testCase.press(testCase.ui.B4)
            testCase.press(testCase.ui.Button_5)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0;4 0 0 0 ;4 0 0 0 ;0 0 0 0 ;  0 0 0 0])
            testCase.press(testCase.ui.B4)
            testCase.press(testCase.ui.Button_5)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B4)
            testCase.press(testCase.ui.Button_6)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0;0 4 0 0 ;0 4 0 0 ;0 0 0 0 ;  0 0 0 0])
            testCase.press(testCase.ui.B4)
            testCase.press(testCase.ui.Button_6)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))


            testCase.press(testCase.ui.B4)
            testCase.press(testCase.ui.Button_7)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0;0 0 4 0 ;0 0 4 0 ;0 0 0 0 ;  0 0 0 0])
            testCase.press(testCase.ui.B4)
            testCase.press(testCase.ui.Button_7)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B4)
            testCase.press(testCase.ui.Button_8)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0;0 0 0 4 ;0 0 0 4 ;0 0 0 0 ;  0 0 0 0])
            testCase.press(testCase.ui.B4)
            testCase.press(testCase.ui.Button_8)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B4)
            testCase.press(testCase.ui.Button_9)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ; 0 0 0 0;4 0 0 0 ;4 0 0 0 ; 0 0 0 0])
            testCase.press(testCase.ui.B4)
            testCase.press(testCase.ui.Button_9)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B4)
            testCase.press(testCase.ui.Button_10)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ; 0 0 0 0;0 4 0 0 ;0 4 0 0 ; 0 0 0 0])
            testCase.press(testCase.ui.B4)
            testCase.press(testCase.ui.Button_10)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B4)
            testCase.press(testCase.ui.Button_11)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ; 0 0 0 0;0 0 4 0 ;0 0 4 0 ; 0 0 0 0])
            testCase.press(testCase.ui.B4)
            testCase.press(testCase.ui.Button_11)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B4)
            testCase.press(testCase.ui.Button_12)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ; 0 0 0 0;0 0 0 4 ;0 0 0 4 ; 0 0 0 0])
            testCase.press(testCase.ui.B4)
            testCase.press(testCase.ui.Button_12)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B4)
            testCase.press(testCase.ui.Button_13)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ; 0 0 0 0; 0 0 0 0;4 0 0 0 ;4 0 0 0 ])
            testCase.press(testCase.ui.B4)
            testCase.press(testCase.ui.Button_13)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B4)
            testCase.press(testCase.ui.Button_14)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ; 0 0 0 0; 0 0 0 0;0 4 0 0 ;0 4 0 0 ])
            testCase.press(testCase.ui.B4)
            testCase.press(testCase.ui.Button_14)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))


            testCase.press(testCase.ui.B4)
            testCase.press(testCase.ui.Button_15)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ; 0 0 0 0; 0 0 0 0;0 0 4 0 ;0 0 4 0 ])
            testCase.press(testCase.ui.B4)
            testCase.press(testCase.ui.Button_15)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B4)
            testCase.press(testCase.ui.Button_16)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0; 0 0 0 0 ; 0 0 0 0;0 0 0 4 ;0 0 0 4 ])
            testCase.press(testCase.ui.B4)
            testCase.press(testCase.ui.Button_16)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))
            

            testCase.press(testCase.ui.B4)
            testCase.press(testCase.ui.Button_17)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))
            testCase.verifyEqual(testCase.ui.Label.Text,'无效操作')
            testCase.press(testCase.ui.B4)
            testCase.press(testCase.ui.Button_18)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))
            testCase.verifyEqual(testCase.ui.Label.Text,'无效操作')
            testCase.press(testCase.ui.B4)
            testCase.press(testCase.ui.Button_19)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))
            testCase.verifyEqual(testCase.ui.Label.Text,'无效操作')
            testCase.press(testCase.ui.B4)
            testCase.press(testCase.ui.Button_20)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))
            testCase.verifyEqual(testCase.ui.Label.Text,'无效操作')
            close all force;
        end
        %T1.6.6
        function operate_chess5_test(testCase)
            testCase.start()
            testCase.press(testCase.ui.B5)
            testCase.press(testCase.ui.Button)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[5 0 0 0 ;5 0 0 0 ;0 0 0 0 ; 0 0 0 0; 0 0 0 0])
            testCase.press(testCase.ui.B5)
            testCase.press(testCase.ui.Button)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B5)
            testCase.press(testCase.ui.Button_2)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 5 0 0 ;0 5 0 0 ;0 0 0 0 ; 0 0 0 0; 0 0 0 0])
            testCase.press(testCase.ui.B5)
            testCase.press(testCase.ui.Button_2)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))


            testCase.press(testCase.ui.B5)
            testCase.press(testCase.ui.Button_3)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 5 0 ;0 0 5 0 ;0 0 0 0 ; 0 0 0 0; 0 0 0 0])
            testCase.press(testCase.ui.B5)
            testCase.press(testCase.ui.Button_3)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B5)
            testCase.press(testCase.ui.Button_4)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 5 ;0 0 0 5 ;0 0 0 0 ; 0 0 0 0; 0 0 0 0])
            testCase.press(testCase.ui.B5)
            testCase.press(testCase.ui.Button_4)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))
            
            testCase.press(testCase.ui.B5)
            testCase.press(testCase.ui.Button_5)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0;5 0 0 0 ;5 0 0 0 ;0 0 0 0 ;  0 0 0 0])
            testCase.press(testCase.ui.B5)
            testCase.press(testCase.ui.Button_5)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B5)
            testCase.press(testCase.ui.Button_6)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0;0 5 0 0 ;0 5 0 0 ;0 0 0 0 ;  0 0 0 0])
            testCase.press(testCase.ui.B5)
            testCase.press(testCase.ui.Button_6)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))


            testCase.press(testCase.ui.B5)
            testCase.press(testCase.ui.Button_7)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0;0 0 5 0 ;0 0 5 0 ;0 0 0 0 ;  0 0 0 0])
            testCase.press(testCase.ui.B5)
            testCase.press(testCase.ui.Button_7)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B5)
            testCase.press(testCase.ui.Button_8)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0;0 0 0 5 ;0 0 0 5 ;0 0 0 0 ;  0 0 0 0])
            testCase.press(testCase.ui.B5)
            testCase.press(testCase.ui.Button_8)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B5)
            testCase.press(testCase.ui.Button_9)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ; 0 0 0 0;5 0 0 0 ;5 0 0 0 ; 0 0 0 0])
            testCase.press(testCase.ui.B5)
            testCase.press(testCase.ui.Button_9)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B5)
            testCase.press(testCase.ui.Button_10)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ; 0 0 0 0;0 5 0 0 ;0 5 0 0 ; 0 0 0 0])
            testCase.press(testCase.ui.B5)
            testCase.press(testCase.ui.Button_10)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B5)
            testCase.press(testCase.ui.Button_11)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ; 0 0 0 0;0 0 5 0 ;0 0 5 0 ; 0 0 0 0])
            testCase.press(testCase.ui.B5)
            testCase.press(testCase.ui.Button_11)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B5)
            testCase.press(testCase.ui.Button_12)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ; 0 0 0 0;0 0 0 5 ;0 0 0 5 ; 0 0 0 0])
            testCase.press(testCase.ui.B5)
            testCase.press(testCase.ui.Button_12)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B5)
            testCase.press(testCase.ui.Button_13)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ; 0 0 0 0; 0 0 0 0;5 0 0 0 ;5 0 0 0 ])
            testCase.press(testCase.ui.B5)
            testCase.press(testCase.ui.Button_13)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B5)
            testCase.press(testCase.ui.Button_14)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ; 0 0 0 0; 0 0 0 0;0 5 0 0 ;0 5 0 0 ])
            testCase.press(testCase.ui.B5)
            testCase.press(testCase.ui.Button_14)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))


            testCase.press(testCase.ui.B5)
            testCase.press(testCase.ui.Button_15)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ; 0 0 0 0; 0 0 0 0;0 0 5 0 ;0 0 5 0 ])
            testCase.press(testCase.ui.B5)
            testCase.press(testCase.ui.Button_15)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B5)
            testCase.press(testCase.ui.Button_16)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0; 0 0 0 0 ; 0 0 0 0;0 0 0 5 ;0 0 0 5 ])
            testCase.press(testCase.ui.B5)
            testCase.press(testCase.ui.Button_16)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))
            

            testCase.press(testCase.ui.B5)
            testCase.press(testCase.ui.Button_17)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))
            testCase.verifyEqual(testCase.ui.Label.Text,'无效操作')
            testCase.press(testCase.ui.B5)
            testCase.press(testCase.ui.Button_18)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))
            testCase.verifyEqual(testCase.ui.Label.Text,'无效操作')
            testCase.press(testCase.ui.B5)
            testCase.press(testCase.ui.Button_19)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))
            testCase.verifyEqual(testCase.ui.Label.Text,'无效操作')
            testCase.press(testCase.ui.B5)
            testCase.press(testCase.ui.Button_20)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))
            testCase.verifyEqual(testCase.ui.Label.Text,'无效操作')
            close all force;
        end
        %T1.6.7
        function operate_chess6_test(testCase)
            testCase.start()
            testCase.press(testCase.ui.B6)
            testCase.press(testCase.ui.Button)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[6 0 0 0 ;6 0 0 0 ;0 0 0 0 ; 0 0 0 0; 0 0 0 0])
            testCase.press(testCase.ui.B6)
            testCase.press(testCase.ui.Button)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B6)
            testCase.press(testCase.ui.Button_2)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 6 0 0 ;0 6 0 0 ;0 0 0 0 ; 0 0 0 0; 0 0 0 0])
            testCase.press(testCase.ui.B6)
            testCase.press(testCase.ui.Button_2)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))


            testCase.press(testCase.ui.B6)
            testCase.press(testCase.ui.Button_3)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 6 0 ;0 0 6 0 ;0 0 0 0 ; 0 0 0 0; 0 0 0 0])
            testCase.press(testCase.ui.B6)
            testCase.press(testCase.ui.Button_3)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B6)
            testCase.press(testCase.ui.Button_4)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 6 ;0 0 0 6 ;0 0 0 0 ; 0 0 0 0; 0 0 0 0])
            testCase.press(testCase.ui.B6)
            testCase.press(testCase.ui.Button_4)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))
            
            testCase.press(testCase.ui.B6)
            testCase.press(testCase.ui.Button_5)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0;6 0 0 0 ;6 0 0 0 ;0 0 0 0 ;  0 0 0 0])
            testCase.press(testCase.ui.B6)
            testCase.press(testCase.ui.Button_5)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B6)
            testCase.press(testCase.ui.Button_6)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0;0 6 0 0 ;0 6 0 0 ;0 0 0 0 ;  0 0 0 0])
            testCase.press(testCase.ui.B6)
            testCase.press(testCase.ui.Button_6)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))


            testCase.press(testCase.ui.B6)
            testCase.press(testCase.ui.Button_7)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0;0 0 6 0 ;0 0 6 0 ;0 0 0 0 ;  0 0 0 0])
            testCase.press(testCase.ui.B6)
            testCase.press(testCase.ui.Button_7)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B6)
            testCase.press(testCase.ui.Button_8)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0;0 0 0 6 ;0 0 0 6 ;0 0 0 0 ;  0 0 0 0])
            testCase.press(testCase.ui.B6)
            testCase.press(testCase.ui.Button_8)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B6)
            testCase.press(testCase.ui.Button_9)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ; 0 0 0 0;6 0 0 0 ;6 0 0 0 ; 0 0 0 0])
            testCase.press(testCase.ui.B6)
            testCase.press(testCase.ui.Button_9)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B6)
            testCase.press(testCase.ui.Button_10)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ; 0 0 0 0;0 6 0 0 ;0 6 0 0 ; 0 0 0 0])
            testCase.press(testCase.ui.B6)
            testCase.press(testCase.ui.Button_10)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B6)
            testCase.press(testCase.ui.Button_11)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ; 0 0 0 0;0 0 6 0 ;0 0 6 0 ; 0 0 0 0])
            testCase.press(testCase.ui.B6)
            testCase.press(testCase.ui.Button_11)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B6)
            testCase.press(testCase.ui.Button_12)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ; 0 0 0 0;0 0 0 6 ;0 0 0 6 ; 0 0 0 0])
            testCase.press(testCase.ui.B6)
            testCase.press(testCase.ui.Button_12)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B6)
            testCase.press(testCase.ui.Button_13)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ; 0 0 0 0; 0 0 0 0;6 0 0 0 ;6 0 0 0 ])
            testCase.press(testCase.ui.B6)
            testCase.press(testCase.ui.Button_13)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B6)
            testCase.press(testCase.ui.Button_14)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ; 0 0 0 0; 0 0 0 0;0 6 0 0 ;0 6 0 0 ])
            testCase.press(testCase.ui.B6)
            testCase.press(testCase.ui.Button_14)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))


            testCase.press(testCase.ui.B6)
            testCase.press(testCase.ui.Button_15)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ; 0 0 0 0; 0 0 0 0;0 0 6 0 ;0 0 6 0 ])
            testCase.press(testCase.ui.B6)
            testCase.press(testCase.ui.Button_15)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B6)
            testCase.press(testCase.ui.Button_16)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0; 0 0 0 0 ; 0 0 0 0;0 0 0 6 ;0 0 0 6 ])
            testCase.press(testCase.ui.B6)
            testCase.press(testCase.ui.Button_16)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))
            

            testCase.press(testCase.ui.B6)
            testCase.press(testCase.ui.Button_17)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))
            testCase.verifyEqual(testCase.ui.Label.Text,'无效操作')
            testCase.press(testCase.ui.B6)
            testCase.press(testCase.ui.Button_18)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))
            testCase.verifyEqual(testCase.ui.Label.Text,'无效操作')
            testCase.press(testCase.ui.B6)
            testCase.press(testCase.ui.Button_19)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))
            testCase.verifyEqual(testCase.ui.Label.Text,'无效操作')
            testCase.press(testCase.ui.B6)
            testCase.press(testCase.ui.Button_20)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))
            testCase.verifyEqual(testCase.ui.Label.Text,'无效操作')
            close all force;
        end
        %T1.6.8
        function operate_chess7_test(testCase)
            testCase.start()
            testCase.press(testCase.ui.B7)
            testCase.press(testCase.ui.Button)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[7 0 0 0 ;0 0 0 0 ;0 0 0 0 ; 0 0 0 0; 0 0 0 0])
            testCase.press(testCase.ui.B7)
            testCase.press(testCase.ui.Button)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B7)
            testCase.press(testCase.ui.Button_2)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 7 0 0 ;0 0 0 0 ;0 0 0 0 ; 0 0 0 0; 0 0 0 0])
            testCase.press(testCase.ui.B7)
            testCase.press(testCase.ui.Button_2)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B7)
            testCase.press(testCase.ui.Button_3)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 7 0 ;0 0 0 0 ;0 0 0 0 ; 0 0 0 0; 0 0 0 0])
            testCase.press(testCase.ui.B7)
            testCase.press(testCase.ui.Button_3)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B7)
            testCase.press(testCase.ui.Button_4)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 7 ;0 0 0 0 ;0 0 0 0 ; 0 0 0 0; 0 0 0 0])
            testCase.press(testCase.ui.B7)
            testCase.press(testCase.ui.Button_4)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))
            
            testCase.press(testCase.ui.B7)
            testCase.press(testCase.ui.Button_5)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0;7 0 0 0 ;0 0 0 0 ;0 0 0 0 ;  0 0 0 0])
            testCase.press(testCase.ui.B7)
            testCase.press(testCase.ui.Button_5)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B7)
            testCase.press(testCase.ui.Button_6)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ;0 7 0 0 ;0 0 0 0 ; 0 0 0 0; 0 0 0 0])
            testCase.press(testCase.ui.B7)
            testCase.press(testCase.ui.Button_6)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B7)
            testCase.press(testCase.ui.Button_7)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0;0 0 7 0 ;0 0 0 0 ;0 0 0 0 ;  0 0 0 0])
            testCase.press(testCase.ui.B7)
            testCase.press(testCase.ui.Button_7)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B7)
            testCase.press(testCase.ui.Button_8)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0;0 0 0 7 ;0 0 0 0 ;0 0 0 0 ;  0 0 0 0])
            testCase.press(testCase.ui.B7)
            testCase.press(testCase.ui.Button_8)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B7)
            testCase.press(testCase.ui.Button_9)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ;0 0 0 0;7 0 0 0 ;0 0 0 0 ;  0 0 0 0])
            testCase.press(testCase.ui.B7)
            testCase.press(testCase.ui.Button_9)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B7)
            testCase.press(testCase.ui.Button_10)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0;0 0 0 0 ;0 7 0 0 ;0 0 0 0 ;  0 0 0 0])
            testCase.press(testCase.ui.B7)
            testCase.press(testCase.ui.Button_10)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B7)
            testCase.press(testCase.ui.Button_11)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ;0 0 0 0;0 0 7 0 ;0 0 0 0 ;  0 0 0 0])
            testCase.press(testCase.ui.B7)
            testCase.press(testCase.ui.Button_11)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B7)
            testCase.press(testCase.ui.Button_12)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ;0 0 0 0;0 0 0 7 ;0 0 0 0 ;  0 0 0 0])
            testCase.press(testCase.ui.B7)
            testCase.press(testCase.ui.Button_12)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B7)
            testCase.press(testCase.ui.Button_13)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ;0 0 0 0 ;0 0 0 0;7 0 0 0 ;  0 0 0 0])
            testCase.press(testCase.ui.B7)
            testCase.press(testCase.ui.Button_13)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B7)
            testCase.press(testCase.ui.Button_14)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ;0 0 0 0;0 0 0 0 ;0 7 0 0 ;  0 0 0 0])
            testCase.press(testCase.ui.B7)
            testCase.press(testCase.ui.Button_14)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B7)
            testCase.press(testCase.ui.Button_15)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ;0 0 0 0 ;0 0 0 0;0 0 7 0 ;  0 0 0 0])
            testCase.press(testCase.ui.B7)
            testCase.press(testCase.ui.Button_15)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B7)
            testCase.press(testCase.ui.Button_16)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ;0 0 0 0 ;0 0 0 0;0 0 0 7 ;  0 0 0 0])
            testCase.press(testCase.ui.B7)
            testCase.press(testCase.ui.Button_16)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B7)
            testCase.press(testCase.ui.Button_17)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ;0 0 0 0;  0 0 0 0 ;0 0 0 0;7 0 0 0 ])
            testCase.press(testCase.ui.B7)
            testCase.press(testCase.ui.Button_17)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B7)
            testCase.press(testCase.ui.Button_18)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ;0 0 0 0;  0 0 0 0;0 0 0 0 ;0 7 0 0 ])
            testCase.press(testCase.ui.B7)
            testCase.press(testCase.ui.Button_18)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B7)
            testCase.press(testCase.ui.Button_19)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ;0 0 0 0 ;  0 0 0 0;0 0 0 0;0 0 7 0 ])
            testCase.press(testCase.ui.B7)
            testCase.press(testCase.ui.Button_19)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B7)
            testCase.press(testCase.ui.Button_20)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ;0 0 0 0;  0 0 0 0 ;0 0 0 0;0 0 0 7 ])
            testCase.press(testCase.ui.B7)
            testCase.press(testCase.ui.Button_20)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))
            close all force
        end
        %T1.6.9
        function operate_chess8_test(testCase)
            testCase.start()
            testCase.press(testCase.ui.B8)
            testCase.press(testCase.ui.Button)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[8 0 0 0 ;0 0 0 0 ;0 0 0 0 ; 0 0 0 0; 0 0 0 0])
            testCase.press(testCase.ui.B8)
            testCase.press(testCase.ui.Button)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B8)
            testCase.press(testCase.ui.Button_2)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 8 0 0 ;0 0 0 0 ;0 0 0 0 ; 0 0 0 0; 0 0 0 0])
            testCase.press(testCase.ui.B8)
            testCase.press(testCase.ui.Button_2)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B8)
            testCase.press(testCase.ui.Button_3)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 8 0 ;0 0 0 0 ;0 0 0 0 ; 0 0 0 0; 0 0 0 0])
            testCase.press(testCase.ui.B8)
            testCase.press(testCase.ui.Button_3)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B8)
            testCase.press(testCase.ui.Button_4)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 8 ;0 0 0 0 ;0 0 0 0 ; 0 0 0 0; 0 0 0 0])
            testCase.press(testCase.ui.B8)
            testCase.press(testCase.ui.Button_4)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))
            
            testCase.press(testCase.ui.B8)
            testCase.press(testCase.ui.Button_5)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0;8 0 0 0 ;0 0 0 0 ;0 0 0 0 ;  0 0 0 0])
            testCase.press(testCase.ui.B8)
            testCase.press(testCase.ui.Button_5)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B8)
            testCase.press(testCase.ui.Button_6)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ;0 8 0 0 ;0 0 0 0 ; 0 0 0 0; 0 0 0 0])
            testCase.press(testCase.ui.B8)
            testCase.press(testCase.ui.Button_6)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B8)
            testCase.press(testCase.ui.Button_7)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0;0 0 8 0 ;0 0 0 0 ;0 0 0 0 ;  0 0 0 0])
            testCase.press(testCase.ui.B8)
            testCase.press(testCase.ui.Button_7)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B8)
            testCase.press(testCase.ui.Button_8)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0;0 0 0 8 ;0 0 0 0 ;0 0 0 0 ;  0 0 0 0])
            testCase.press(testCase.ui.B8)
            testCase.press(testCase.ui.Button_8)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B8)
            testCase.press(testCase.ui.Button_9)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ;0 0 0 0;8 0 0 0 ;0 0 0 0 ;  0 0 0 0])
            testCase.press(testCase.ui.B8)
            testCase.press(testCase.ui.Button_9)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B8)
            testCase.press(testCase.ui.Button_10)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0;0 0 0 0 ;0 8 0 0 ;0 0 0 0 ;  0 0 0 0])
            testCase.press(testCase.ui.B8)
            testCase.press(testCase.ui.Button_10)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B8)
            testCase.press(testCase.ui.Button_11)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ;0 0 0 0;0 0 8 0 ;0 0 0 0 ;  0 0 0 0])
            testCase.press(testCase.ui.B8)
            testCase.press(testCase.ui.Button_11)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B8)
            testCase.press(testCase.ui.Button_12)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ;0 0 0 0;0 0 0 8 ;0 0 0 0 ;  0 0 0 0])
            testCase.press(testCase.ui.B8)
            testCase.press(testCase.ui.Button_12)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B8)
            testCase.press(testCase.ui.Button_13)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ;0 0 0 0 ;0 0 0 0;8 0 0 0 ;  0 0 0 0])
            testCase.press(testCase.ui.B8)
            testCase.press(testCase.ui.Button_13)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B8)
            testCase.press(testCase.ui.Button_14)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ;0 0 0 0;0 0 0 0 ;0 8 0 0 ;  0 0 0 0])
            testCase.press(testCase.ui.B8)
            testCase.press(testCase.ui.Button_14)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B8)
            testCase.press(testCase.ui.Button_15)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ;0 0 0 0 ;0 0 0 0;0 0 8 0 ;  0 0 0 0])
            testCase.press(testCase.ui.B8)
            testCase.press(testCase.ui.Button_15)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B8)
            testCase.press(testCase.ui.Button_16)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ;0 0 0 0 ;0 0 0 0;0 0 0 8 ;  0 0 0 0])
            testCase.press(testCase.ui.B8)
            testCase.press(testCase.ui.Button_16)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B8)
            testCase.press(testCase.ui.Button_17)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ;0 0 0 0;  0 0 0 0 ;0 0 0 0;8 0 0 0 ])
            testCase.press(testCase.ui.B8)
            testCase.press(testCase.ui.Button_17)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B8)
            testCase.press(testCase.ui.Button_18)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ;0 0 0 0;  0 0 0 0;0 0 0 0 ;0 8 0 0 ])
            testCase.press(testCase.ui.B8)
            testCase.press(testCase.ui.Button_18)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B8)
            testCase.press(testCase.ui.Button_19)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ;0 0 0 0 ;  0 0 0 0;0 0 0 0;0 0 8 0 ])
            testCase.press(testCase.ui.B8)
            testCase.press(testCase.ui.Button_19)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B8)
            testCase.press(testCase.ui.Button_20)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ;0 0 0 0;  0 0 0 0 ;0 0 0 0;0 0 0 8 ])
            testCase.press(testCase.ui.B8)
            testCase.press(testCase.ui.Button_20)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))
            close all force
        end
        %T1.6.10
        function operate_chess9_test(testCase)
            testCase.start()
            testCase.press(testCase.ui.B9)
            testCase.press(testCase.ui.Button)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[9 0 0 0 ;0 0 0 0 ;0 0 0 0 ; 0 0 0 0; 0 0 0 0])
            testCase.press(testCase.ui.B9)
            testCase.press(testCase.ui.Button)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B9)
            testCase.press(testCase.ui.Button_2)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 9 0 0 ;0 0 0 0 ;0 0 0 0 ; 0 0 0 0; 0 0 0 0])
            testCase.press(testCase.ui.B9)
            testCase.press(testCase.ui.Button_2)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B9)
            testCase.press(testCase.ui.Button_3)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 9 0 ;0 0 0 0 ;0 0 0 0 ; 0 0 0 0; 0 0 0 0])
            testCase.press(testCase.ui.B9)
            testCase.press(testCase.ui.Button_3)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B9)
            testCase.press(testCase.ui.Button_4)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 9 ;0 0 0 0 ;0 0 0 0 ; 0 0 0 0; 0 0 0 0])
            testCase.press(testCase.ui.B9)
            testCase.press(testCase.ui.Button_4)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))
            
            testCase.press(testCase.ui.B9)
            testCase.press(testCase.ui.Button_5)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0;9 0 0 0 ;0 0 0 0 ;0 0 0 0 ;  0 0 0 0])
            testCase.press(testCase.ui.B9)
            testCase.press(testCase.ui.Button_5)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B9)
            testCase.press(testCase.ui.Button_6)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ;0 9 0 0 ;0 0 0 0 ; 0 0 0 0; 0 0 0 0])
            testCase.press(testCase.ui.B9)
            testCase.press(testCase.ui.Button_6)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B9)
            testCase.press(testCase.ui.Button_7)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0;0 0 9 0 ;0 0 0 0 ;0 0 0 0 ;  0 0 0 0])
            testCase.press(testCase.ui.B9)
            testCase.press(testCase.ui.Button_7)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B9)
            testCase.press(testCase.ui.Button_8)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0;0 0 0 9 ;0 0 0 0 ;0 0 0 0 ;  0 0 0 0])
            testCase.press(testCase.ui.B9)
            testCase.press(testCase.ui.Button_8)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B9)
            testCase.press(testCase.ui.Button_9)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ;0 0 0 0;9 0 0 0 ;0 0 0 0 ;  0 0 0 0])
            testCase.press(testCase.ui.B9)
            testCase.press(testCase.ui.Button_9)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B9)
            testCase.press(testCase.ui.Button_10)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0;0 0 0 0 ;0 9 0 0 ;0 0 0 0 ;  0 0 0 0])
            testCase.press(testCase.ui.B9)
            testCase.press(testCase.ui.Button_10)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B9)
            testCase.press(testCase.ui.Button_11)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ;0 0 0 0;0 0 9 0 ;0 0 0 0 ;  0 0 0 0])
            testCase.press(testCase.ui.B9)
            testCase.press(testCase.ui.Button_11)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B9)
            testCase.press(testCase.ui.Button_12)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ;0 0 0 0;0 0 0 9 ;0 0 0 0 ;  0 0 0 0])
            testCase.press(testCase.ui.B9)
            testCase.press(testCase.ui.Button_12)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B9)
            testCase.press(testCase.ui.Button_13)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ;0 0 0 0 ;0 0 0 0;9 0 0 0 ;  0 0 0 0])
            testCase.press(testCase.ui.B9)
            testCase.press(testCase.ui.Button_13)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B9)
            testCase.press(testCase.ui.Button_14)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ;0 0 0 0;0 0 0 0 ;0 9 0 0 ;  0 0 0 0])
            testCase.press(testCase.ui.B9)
            testCase.press(testCase.ui.Button_14)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B9)
            testCase.press(testCase.ui.Button_15)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ;0 0 0 0 ;0 0 0 0;0 0 9 0 ;  0 0 0 0])
            testCase.press(testCase.ui.B9)
            testCase.press(testCase.ui.Button_15)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B9)
            testCase.press(testCase.ui.Button_16)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ;0 0 0 0 ;0 0 0 0;0 0 0 9 ;  0 0 0 0])
            testCase.press(testCase.ui.B9)
            testCase.press(testCase.ui.Button_16)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B9)
            testCase.press(testCase.ui.Button_17)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ;0 0 0 0;  0 0 0 0 ;0 0 0 0;9 0 0 0 ])
            testCase.press(testCase.ui.B9)
            testCase.press(testCase.ui.Button_17)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B9)
            testCase.press(testCase.ui.Button_18)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ;0 0 0 0;  0 0 0 0;0 0 0 0 ;0 9 0 0 ])
            testCase.press(testCase.ui.B9)
            testCase.press(testCase.ui.Button_18)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B9)
            testCase.press(testCase.ui.Button_19)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ;0 0 0 0 ;  0 0 0 0;0 0 0 0;0 0 9 0 ])
            testCase.press(testCase.ui.B9)
            testCase.press(testCase.ui.Button_19)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B9)
            testCase.press(testCase.ui.Button_20)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ;0 0 0 0;  0 0 0 0 ;0 0 0 0;0 0 0 9 ])
            testCase.press(testCase.ui.B9)
            testCase.press(testCase.ui.Button_20)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))
            close all force
        end
        %T1.6.11
        function operate_chess10_test(testCase)
            testCase.start()
            testCase.press(testCase.ui.B10)
            testCase.press(testCase.ui.Button)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[10 0 0 0 ;0 0 0 0 ;0 0 0 0 ; 0 0 0 0; 0 0 0 0])
            testCase.press(testCase.ui.B10)
            testCase.press(testCase.ui.Button)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B10)
            testCase.press(testCase.ui.Button_2)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 10 0 0 ;0 0 0 0 ;0 0 0 0 ; 0 0 0 0; 0 0 0 0])
            testCase.press(testCase.ui.B10)
            testCase.press(testCase.ui.Button_2)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B10)
            testCase.press(testCase.ui.Button_3)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 10 0 ;0 0 0 0 ;0 0 0 0 ; 0 0 0 0; 0 0 0 0])
            testCase.press(testCase.ui.B10)
            testCase.press(testCase.ui.Button_3)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B10)
            testCase.press(testCase.ui.Button_4)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 10 ;0 0 0 0 ;0 0 0 0 ; 0 0 0 0; 0 0 0 0])
            testCase.press(testCase.ui.B10)
            testCase.press(testCase.ui.Button_4)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))
            
            testCase.press(testCase.ui.B10)
            testCase.press(testCase.ui.Button_5)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0;10 0 0 0 ;0 0 0 0 ;0 0 0 0 ;  0 0 0 0])
            testCase.press(testCase.ui.B10)
            testCase.press(testCase.ui.Button_5)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B10)
            testCase.press(testCase.ui.Button_6)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ;0 10 0 0 ;0 0 0 0 ; 0 0 0 0; 0 0 0 0])
            testCase.press(testCase.ui.B10)
            testCase.press(testCase.ui.Button_6)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B10)
            testCase.press(testCase.ui.Button_7)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0;0 0 10 0 ;0 0 0 0 ;0 0 0 0 ;  0 0 0 0])
            testCase.press(testCase.ui.B10)
            testCase.press(testCase.ui.Button_7)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B10)
            testCase.press(testCase.ui.Button_8)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0;0 0 0 10 ;0 0 0 0 ;0 0 0 0 ;  0 0 0 0])
            testCase.press(testCase.ui.B10)
            testCase.press(testCase.ui.Button_8)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B10)
            testCase.press(testCase.ui.Button_9)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ;0 0 0 0;10 0 0 0 ;0 0 0 0 ;  0 0 0 0])
            testCase.press(testCase.ui.B10)
            testCase.press(testCase.ui.Button_9)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B10)
            testCase.press(testCase.ui.Button_10)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0;0 0 0 0 ;0 10 0 0 ;0 0 0 0 ;  0 0 0 0])
            testCase.press(testCase.ui.B10)
            testCase.press(testCase.ui.Button_10)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B10)
            testCase.press(testCase.ui.Button_11)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ;0 0 0 0;0 0 10 0 ;0 0 0 0 ;  0 0 0 0])
            testCase.press(testCase.ui.B10)
            testCase.press(testCase.ui.Button_11)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B10)
            testCase.press(testCase.ui.Button_12)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ;0 0 0 0;0 0 0 10 ;0 0 0 0 ;  0 0 0 0])
            testCase.press(testCase.ui.B10)
            testCase.press(testCase.ui.Button_12)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B10)
            testCase.press(testCase.ui.Button_13)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ;0 0 0 0 ;0 0 0 0;10 0 0 0 ;  0 0 0 0])
            testCase.press(testCase.ui.B10)
            testCase.press(testCase.ui.Button_13)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B10)
            testCase.press(testCase.ui.Button_14)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ;0 0 0 0;0 0 0 0 ;0 10 0 0 ;  0 0 0 0])
            testCase.press(testCase.ui.B10)
            testCase.press(testCase.ui.Button_14)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B10)
            testCase.press(testCase.ui.Button_15)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ;0 0 0 0 ;0 0 0 0;0 0 10 0 ;  0 0 0 0])
            testCase.press(testCase.ui.B10)
            testCase.press(testCase.ui.Button_15)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B10)
            testCase.press(testCase.ui.Button_16)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ;0 0 0 0 ;0 0 0 0;0 0 0 10 ;  0 0 0 0])
            testCase.press(testCase.ui.B10)
            testCase.press(testCase.ui.Button_16)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B10)
            testCase.press(testCase.ui.Button_17)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ;0 0 0 0;  0 0 0 0 ;0 0 0 0;10 0 0 0 ])
            testCase.press(testCase.ui.B10)
            testCase.press(testCase.ui.Button_17)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B10)
            testCase.press(testCase.ui.Button_18)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ;0 0 0 0;  0 0 0 0;0 0 0 0 ;0 10 0 0 ])
            testCase.press(testCase.ui.B10)
            testCase.press(testCase.ui.Button_18)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B10)
            testCase.press(testCase.ui.Button_19)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ;0 0 0 0 ;  0 0 0 0;0 0 0 0;0 0 10 0 ])
            testCase.press(testCase.ui.B10)
            testCase.press(testCase.ui.Button_19)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))

            testCase.press(testCase.ui.B10)
            testCase.press(testCase.ui.Button_20)
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),[0 0 0 0 ;0 0 0 0;  0 0 0 0 ;0 0 0 0;0 0 0 10 ])
            testCase.press(testCase.ui.B10)
            testCase.press(testCase.ui.Button_20)
            testCase.verifyEqual(testCase.ui.Label.Text,'请选择操作按键')
            testCase.verifyEqual(testCase.ui.chessboard.get_chessboard(),zeros(5,4))
            close all force
        end
    end
end

